spring.application.name=SLF4J


spring.datasource.url=jdbc:postgresql://localhost:5432/medical_db
spring.datasource.username=postgres
spring.datasource.password=lehqwuoc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


# LOGGING

logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.medical.service=TRACE

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# LOG FILE

logging.file.name=logs/patient_web_service.log
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.file-name-pattern=logs/patient_web_service-%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=50MB